### ISSUE TITLE
Refactor codebase

### ISSUE THREAD

**Issue by anthonyryan1** [fagga/transmission-remote-cli#159]
The way things are currently structured isn't very easy to maintain. With all of the code in a single file just under 4000 lines long and a handful of conditional features, I think it might be time to refactor the code.

Since [we](https://github.com/whatbox) are interested in replacing [geoip](https://pypi.python.org/pypi/GeoIP/) with [geoip2](https://pypi.python.org/pypi/geoip2) and I can understand the hesitation to accept such changes. I was hoping we could help get things moving towards a more maintainable code base so we can later make the changes we're after.

@fagga The main things I would like to know is if you have any vision for how you'd like to see things structured. As the person with the most hands on experience with this codebase I feel like we should get your guidance and establish a solid plan before we attempt any code.

My opinion (as a person who is fairly new to this codebase) is that we should break it into class responsible for managing each part of the interface (eg: a table of peers) that would be responsible for the interface and have a separate "plugin" for every piece of information displayed within (eg: a country column for geoip lookups). I'm not particularly experienced with python plugin systems, but we could use a popular library like [yapsy](https://pypi.python.org/pypi/Yapsy) to avoid reinventing the wheel.

I look forward to your input.

**Comment by fagga** [comment]
Well, the way I would restructure is to dump everything and start from scratch. There are so many bad decisions I've made, I don't know where to start.

Most importantly: The name is just wrong! At the time I was so excited about writing code, and I absolutely did not expect that kind of popularity, so I just picked the first name that came to me. And now there's a CLI client called "transmission-remote" and a TUI client called "transmission-remote-cli". I can't think of a more confusing naming scheme.

Really most importantly: Re-use existing code! Using curses directly, for example, was a terrible decision. The way curses does things is definitely not the way you want to think about UI code in Python. This will always cause bugs and prevent new features because you have to reinvent the wheel. For example, it's currently impossible to use meta for key combinations, and adding that feature would add wonky code that was written and tested years ago in modules like Urwid. Even writing my own abstraction module would've been better.

I also should've properly decoupled IPC from user interaction; Twisted was probably already around at the time, and nowadays something based on asyncio may be even better, I don't know.

My main advice is that you shouldn't invest too much time in this huge pile of workarounds and spaghetti code, if only because I, the maintainer, am not really motivated to do that either.

Sorry, all of that must be pretty disappointing.

I don't know anything about geoip2 (or geoip, for that matter; that code was contributed by someone else). What would making that switch entail?

**Comment by anthonyryan1** [comment]
Based on what you're saying, how I'd approach the geoip problem is to simply remove the existing geoip code and put calls in the new library (probably ~40 lines changed) all of which would be within `if features['geoip']:` and removing `if features['ipy']:` because geoip2 handles IPv6 without the need for another library.

The only drawback with this approach is that it will require people to install geoip2 to continue using this feature, people using it now will find that feature disabled unless they upgrade that.

**Comment by fagga** [comment]
Removing IPy would be a simplification; sounds great. On the other hand,
geoip2 isn't even in Debian. Users would have to manually install it to get
the same functionality, which doesn't sound that great. Then again, maybe
someone would package it. Or maybe not.

The switch to geoip2 wouldn't have any visible effects, correct? Sounds like a
bad reason to break stuff from a user perspective.

Why do you have to *replace* geoip with geoip2? Can't you have both installed
alongside?

Or what about keeping a patched version on your servers? The amount of work to
keep it up-to-date should be minimal to zero, considering that development has
effectively stopped.

**Comment by anthonyryan1** [comment]
My first idea was to support both (geoip and geoip2), but that would add more code and more complexity, which is what made me think refactoring was a prerequisite.

If refactoring is out of the question, then replacing the existing approach seemed like the next best plan. It gives an opportunity to actually reduce the complexity a little rather than adding more.

We can certainly carry a patch for this. We just try to contribute back to the software we include on our servers.

**Comment by fagga** [comment]
Thank you for contributing (or trying to :). It's appreciated.

Your reasoning makes sense, but the code as it is works better than your
proposal, at least from a user perspective (no need to hunt for geoip2), and
the maintainability wouldn't increase significantly as the major problems I
outlined earlier would still exist.

So I think it's better to not touch anything for now. If you want, you can
submit a pull request anyway in case this becomes relevant in the future.
