### ISSUE TITLE
Allow prioritisation of files in a torrent

### ISSUE THREAD

**Issue by bernd-wechner** [fagga/transmission-remote-cli#172]
Oops, blundered here, this should be with transmisison proper! Apologies. Moreover it's already possible in Transmission, was just hidden in a dialog box too narrow for me to see ;-). Gotta love this client.  Would delete this issue if I knew how.

**Comment by fagga** [comment]
This is already implemented. Select a torrent, 'f' for files view, move
up/down to select a file, move right/left to change priority.

> The beauty of Github of course fagga, is that you don't have to implement this

Yeah, but I have to maintain it. What I learned from this project (among other
things) is that you shouldn't accept pull requests just because they seem to
work fine. They have to integrate nicely into the rest of the code or you'll
quickly end up in a situation where you touch something here, something over
there explodes for no reason.

> Seen too many die because one person held control then disappeared from the
> world. Github won't even help and a fork by some new champ and hence project
> rename for differentiation is all that's left as an option.

Nobody has made a fork because nobody likes wading through a metric ton of
criminally messy code, especially if it's not your own mess. A complete
rewrite would be easier and faster than putting this project into a
maintainable state.
